<option value="add">Add</option>
<option value="address-book">Address Book</option>
<option value="anchor">Anchor Link</option>
<option value="attach">Attachment</option>
<option value="award">Award</option>
<option value="basket">Basket</option>
<option value="battery">Battery</option>
<option value="battery-full">Battery Full</option>
<option value="battery-half">Battery Half</option>
<option value="battery-low">Battery Low</option>
<option value="bell">Bell</option>
<option value="box">Box</option>
<option value="box-down">Box Down</option>
<option value="brain">Brain</option>
<option value="brain-trainer">Brain Trainer</option>
<option value="brick">Brick</option>
<option value="briefcase">Briefcase</option>
<option value="bug">Bug</option>
<option value="butterfly">Butterfly</option>
<option value="cake">Cake</option>
<option value="calendar">Calendar</option>
<option value="camera">Camera</option>
<option value="car">Car</option>
<option value="calendar">Calendar</option>
<option value="cart">Cart</option>
<option value="cat">Cat</option>
<option value="cd">CD</option>
<option value="chair">Chair</option>
<option value="chameleon">Chameleon</option>
<option value="chart-bar">Chart Bar</option>
<option value="chart-pie">Chart Pie</option>
<option value="chess-horse">Chess Horse</option>
<option value="chess-tower">Chess Tower</option>
<option value="clock">Clock</option>
<option value="cog">Cog</option>
<option value="coins">Coins</option>
<option value="cold">Cold</option>
<option value="color-picker">Color Picker</option>
<option value="compress">Compress</option>
<option value="computer">Computer</option>
<option value="connect">Connect</option>
<option value="construction">Construction</option>
<option value="control-play">Control Play</option>
<option value="controller">Controller</option>
<option value="creditcards">Credit Cards</option>
<option value="cross">Cross</option>
<option value="cup">Cup</option>
<option value="cursor">Cursor</option>
<option value="cut">Cut</option>
<option value="date">Date</option>
<option value="disconnect">Disconnect</option>
<option value="document-info">Document Info</option>
<option value="dog">Dog</option>
<option value="door">Door</option>
<option value="-draw-clone">Drawclone</option>
<option value="draw-convolve">Draw Convolve</option>
<option value="draw-ink">Draw Ink</option>
<option value="draw-smudge">Draw Smudge</option>
<option value="drink">Drink</option>
<option value="drum">Drum</option>
<option value="dynamite">Dynamite</option>
<option value="education">Education</option>
<option value="email">Email</option>
<option value="error">Error</option>
<option value="events">Events</option>
<option value="exclamation">Exclamation</option>
<option value="extinguisher">Extinguisher</option>
<option value="external">External</option>
<option value="eye">Eye</option>
<option value="feed">Eeed</option>
<option value="female">Female</option>
<option value="film">Film</option>
<option value="filter">Filter</option>
<option value="find">Find</option>
<option value="flag">Flag</option>
<option value="flashdisk">Flashdisk</option>
<option value="flower">Flower</option>
<option value="folder">Folder</option>
<option value="gmap">Gmap</option>
<option value="group">Group</option>
<option value="hammer">Hammer</option>
<option value="handbag">Handbag</option>
<option value="hat">Hat</option>
<option value="headphones">Headphones</option>
<option value="health">Health</option>
<option value="heart">Heart</option>
<option value="help">Help</option>
<option value="horoscopes">Horoscopes</option>
<option value="hot">Hot</option>
<option value="hotjobs">Hotjobs</option>
<option value="house">House</option>
<option value="icecream">Ice Cream</option>
<option value="image">Image</option>
<option value="images">Images</option>
<option value="info">Info</option>
<option value="installer">Installer</option>
<option value="ipod">Ipod</option>
<option value="joystick">Joystick</option>
<option value="key">Key</option>
<option value="keyboard">Keyboard</option>
<option value="layout">Layout</option>
<option value="leaf">Leaf</option>
<option value="lightbulb">Lightbulb</option>
<option value="lightbulb-off">Lightbulb Off</option>
<option value="lifesafe">Lifesafe</option>
<option value="lightning">Lightning</option>
<option value="link">Link</option>
<option value="location">Location</option>
<option value="lock">Lock</option>
<option value="lock-break">Lock Break</option>
<option value="lock-open">Lock Open</option>
<option value="lollipop">Lollipop</option>
<option value="lorry">Lorry</option>
<option value="magnifier">Magnifier</option>
<option value="mailbox">Mailbox</option>
<option value="male">Male</option>
<option value="map">Map</option>
<option value="marker">Marker</option>
<option value="marketwatch">Marketwatch</option>
<option value="measure">Measure</option>
<option value="microphone">Microphone</option>
<option value="money">Money</option>
<option value="money-bag">Money Bag</option>
<option value="money-dollar">Money Dollar</option>
<option value="monitor">Monitor</option>
<option value="mouse">Mouse</option>
<option value="movies">Movies</option>
<option value="music">Music</option>
<option value="newspaper">Newspaper</option>
<option value="note">Note</option>
<option value="package">Package</option>
<option value="page">Page</option>
<option value="paypal">Paypal</option>
<option value="pencil">Pencil</option>
<option value="photo">Photo</option>
<option value="picture-frame">Picture Frame</option>
<option value="pictures">Pictures</option>
<option value="pill">Pill</option>
<option value="plant">Plant</option>
<option value="plugin">Plugin</option>
<option value="poker">Poker</option>
<option value="printer">Printer</option>
<option value="radio">Radio</option>
<option value="rain">Rain</option>
<option value="rainbow">Rainbow</option>
<option value="recycle">Recycle</option>
<option value="report">Report</option>
<option value="reseller">Reseller</option>
<option value="resize">Resize</option>
<option value="ribbon">Ribbon</option>
<option value="rosette">Rosette</option>
<option value="rss">RSS</option>
<option value="ruby">Ruby</option>
<option value="safe">Safe</option>
<option value="santa">Santa</option>
<option value="satellite">Satellite</option>
<option value="screwdriver">Screwdriver</option>
<option value="script">Script</option>
<option value="select">Select</option>
<option value="shopping">Shopping</option>
<option value="showel">Showel</option>
<option value="shuriken">Shuriken</option>
<option value="skate">Skate</option>
<option value="sound">Sound</option>
<option value="sound-mute">Sound Mute</option>
<option value="speedometer">Speedometer</option>
<option value="spider">Spider</option>
<option value="basketball">Sport Basketball</option>
<option value="football">Sport Football</option>
<option value="golf">Sport Golf</option>
<option value="soccer">Sport Soccer</option>
<option value="tennis">Sport Tennis</option>
<option value="star">Star</option>
<option value="offline">Status Offline</option>
<option value="online">Status Online</option>
<option value="stop">Stop</option>
<option value="support">Support</option>
<option value="tag">Tag</option>
<option value="teddy">Teddy</option>
<option value="telephone">Telephone</option>
<option value="temperature">Temperature</option>
<option value="lips">Lips</option>
<option value="thumbdown">Thumbdown</option>
<option value="thumbup">Thumbup</option>
<option value="tick">Tick</option>
<option value="time">Time</option>
<option value="toolbox">Toolbox</option>
<option value="tornado">Tornado</option>
<option value="toucan">Toucan</option>
<option value="toxic">Toxic</option>
<option value="transmit">Transmit</option>
<option value="travel">Travel</option>
<option value="tree">Tree</option>
<option value="twitter">Twitter</option>
<option value="umbrella">Umbrella</option>
<option value="user">User</option>
<option value="user-comment">User Comment</option>
<option value="vcard">vCard</option>
<option value="video">Video</option>
<option value="walk">Walk</option>
<option value="wand">Wand</option>
<option value="sun">Sun</option>
<option value="webcam">Webcam</option>
<option value="weight">Weight</option>
<option value="whistle">Whistle</option>
<option value="wordpress">Wordpress</option>
<option value="world">World</option>
<option value="zoom">Zoom</option>
<option value="zoom-selection">Zoom Selection</option>